# Generated by Django 4.2.2 on 2023-07-08 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('BNAME', models.CharField(max_length=100)),
                ('BID', models.IntegerField(primary_key=True, serialize=False)),
                ('BPRICE', models.CharField(max_length=100)),
                ('BMODEL', models.CharField(max_length=100)),
                ('BCAPACITY', models.CharField(max_length=100)),
                ('BWEIGHT', models.CharField(max_length=100)),
                ('BMILEAGE', models.CharField(max_length=100)),
                ('BIMAGE', models.ImageField(upload_to='')),
                ('USERNAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
