# Generated by Django 4.2.2 on 2023-07-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='DESCRIPTION',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
